config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, skip: [:registrations], controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    get 'cabinet' => 'users/registrations#show'
    get 'cabinet/edit' => 'users/registrations#edit'
    put 'cabinet' => 'users/registrations#update'
  end

  resources :groups
  resources 'nodes'
  resources 'accounts'
  resources 'messages'
  resources 'vk_groups'
  resources 'groups'
  resources :mass_mailings do
    member do
      get :retry
    end
  end

  resources :mass_mailing_nodes, controller: 'mass_mailing_nodes'
  resources :statistics, controller: 'statistics'

  root 'mass_mailings#index'
  resources :node_vks, controller: 'nodes', type: 'Node::Vk'
  resources :node_emails, controller: 'nodes', type: 'Node::Email'

  mount Resque::Server.new, at: "/resque"

end

app/models/message.rb
class Message < ActiveRecord::Base
  #attr_reader :pic1_remote
  #attr_reader :pic1_file_name
  has_many :taggings, as: :taggable
  has_many :mass_mailing, through: :mass_mailing_nodes
  acts_as_taggable
  has_attached_file :pic1, path: ":rails_root/public/images/attachments/:filename"
  has_attached_file :doc1, path: ":rails_root/public/docs/attachments/:filename"
  validates_attachment :pic1, pic1_content_type: ["image/jpeg", "image/gif", "image/png"]
  validates_attachment_file_name :pic1, matches: [/png\Z/, /jpe?g\Z/]

  validates :title, presence: true
  validates :content, presence: true

  #validates_attachment_content_type :pic1, content_type: /\Aimage\/.*\Z/
  #validates_attachment :pic1, pic1_file_name: matches: [/png\Z/, /jpe?g\Z/]#["image/jpeg", "image/gif", "image/png"]

  scope :includes_tags, -> { includes(:tags) }


  def self.search(query)
    # TODO: Fix search
    # additional_ids = NodeIdsWhereTagNameMatch.query(query).join(",")
    # where("title ILIKE :search OR content ILIKE :search OR ARRAY[id] <@ ARRAY[#{additional_ids}]::integer[]",
    #       search: "%#{query}%")
    where('title ILIKE :search OR content ILIKE :search', search: "%#{query}%")
  end
# Will be corrected to enable attachment from remote
=begin
   def pic1_remote=(url)

    @pic1_remote = url
    self.pic1 = URI.parse(url)
    byebug
    self.pic1 = URI.parse(url)
  end
=end

  def load_attachments
    {}.tap do |hash|
      hash[pic1_name.to_s] = File.read(pic1_path) if pic1_exist?
      hash[doc1_name.to_s] = File.read(doc1_path) if doc1_exist?
    end
  end

  def tag_list_name
    tags.map(&:name).join('; ')
  end

  def pic1_exist?
    File.exist?(pic1_path)
  end

  def pic1_path
    attachment_path(pic1_file_name)
  end

  def doc1_path
    attachment_path(doc1_file_name)
  end

  def doc1_exist?
    File.exist?(doc1_path)
  end

  def attacments?
    doc1_exist? || pic1_exist?
  end

  def attachment_path(name)
    if name.present?
      "#{Rails.root.to_s}/public/images/attachments/#{name}"
    else
      ''
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  load_and_authorize_resource
  before_filter :board
  def index
    respond_to do |format|
      format.html
      format.json { render json: DataTable::Messages.new(view_context) }
    end
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    b.message = Message.new(message_params)
    respond_to do |format|
      if b.message.save
        format.html { redirect_to b.message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: b.message }
      else
        format.html { render :new }
        format.json { render json: b.message.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if b.message.update(message_params)
        format.html { redirect_to b.message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: b.message }
      else
        format.html { render :edit }
        format.json { render json: b.message.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    b.message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def message_params
    params.require('message')
          .permit(:title, :content, :tag_list, :pic1, :doc1)
  end

  def board
    @board ||= MessagesBoard.new(self)
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= simple_form_for(b.message, defaults: { input_html: { class: 'form-horizontal' } }) do |f| %>
  <%= f.input :title, required: true %>
  <%= f.input :content, as: :text, input_html: { rows: 20 }, required: true%>
  <%= f.input :tag_list %>
  Attach files:
  <br>
  <div class="form-group">
    Picture: <%= f.file_field :pic1%><br>
    <button class="btn btn-danger btn-xs" id="btn-reset-picture">Remove picture</button>
  </div>
  <div class="form-group">
    Any document: <%= f.file_field :doc1%><br>
    <button class="btn btn-danger btn-xs" id="btn-reset-file">Remove file</button>
  </div>
  <br>
  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

app/views/messages/edit.html.erb
<h1><%= t('message.edit') %></h1>

<%= render 'form' %>
<br>
<%= link_to t('show'), b.message %> |
<%= link_to t('back'), messages_path %>

app/views/messages/index.html.erb
<div class="row header header_row">
  <div class="col-md-11">
    <h1><%= t('listing_messages') %></h1>
  </div>
  <div class="col-md-1">
    <% if can? :create, Message %>
      <%= link_to glyphicon_with_text('plus', t('new_message')), new_message_path, class: 'btn btn-primary pull-right' %>
    <% end %>
  </div>
</div>
<br>
<div class="row">
  <div class="col-md-12">
    <table class='table' id="nodes" data-source="<%= messages_url(format: :json)%>">
      <thead>
        <tr>
          <th>ID</th>
          <th><%= Message.human_attribute_name('title') %></th>
          <th><%= Message.human_attribute_name('content') %></th>
          <th><%= Message.human_attribute_name('tags') %></th>
          <% if can? :update, Node %>
            <th><%= t('edit') %></th>
            <th><%= t('destroy') %></th>
          <% end %>
        </tr>
      </thead>
        <% b.messages.each do |message| %>
          <tr>
            <td><%= message.id %></td>
            <td><%= message.title %></td>
            <td><%= truncate(ERB::Util.h(message.content), length: 300) %></td>
            <td><%= message.tag_list_name %></td>
            <% if can? :update, Node %>
              <td><%= link_to(t('edit'), edit_message_path(message)) %></td>
              <td><%= link_to(t('destroy'), message, method: :delete, data: { confirm: t('confirmation') }) %></td>
            <% end %>
          </tr>
        <% end %>
      <tbody>
      </tbody>
    </table>
  </div>
</div>

app/views/messages/new.html.erb
<h1><%= t('message.new') %></h1>

<%= render 'form' %>
<br>
<%= link_to t('back'), messages_path %>

app/views/messages/show.html.slim
.row.header.header_row
  .col-md-10
    h1
      = b.message.title
      = tag_badges(b.message_tags)
  .col-md-2
    .header_toolbar.pull-right
      = link_to glyphicon_with_text('pencil', 'Edit'), edit_message_path(b.message), class: 'btn btn-primary pull-right'

br
.row
  .col-md-12
    = simple_format(b.message.content)
.row
  .col-md-12
    - if b.message.attacments?
      h1 Attached files:
      .col-md-12
        ul
          - if b.message.pic1_exist?
            li
               = b.message.pic1_file_name
          - if b.message.doc1_exist?
            li
              = b.message.doc1_file_name
.row
  .col-md-12
    = link_to t('back'), mass_mailings_path, class: 'btn btn-default'