config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, skip: [:registrations], controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    get 'cabinet' => 'users/registrations#show'
    get 'cabinet/edit' => 'users/registrations#edit'
    put 'cabinet' => 'users/registrations#update'
  end

  resources :groups
  resources 'nodes'
  resources 'accounts'
  resources 'messages'
  resources 'vk_groups'
  resources 'groups'
  resources :mass_mailings do
    member do
      get :retry
    end
  end

  resources :mass_mailing_nodes, controller: 'mass_mailing_nodes'
  resources :statistics, controller: 'statistics'

  root 'mass_mailings#index'
  resources :node_vks, controller: 'nodes', type: 'Node::Vk'
  resources :node_emails, controller: 'nodes', type: 'Node::Email'

  mount Resque::Server.new, at: "/resque"

end

app/models/group.rb
class Group < ActiveRecord::Base
  include Errorable

  self.table_name = 'tags'
  has_many :taggings, foreign_key: 'tag_id'
  has_many :nodes, through: :taggings, source: :taggable, source_type: 'Node'

  accepts_nested_attributes_for :taggings, allow_destroy: true

  validates :taggings, length: { minimum: 1 }
  validates :name, length: { minimum: 3 }

  scope :groups, -> { joins(:taggings).where(taggings: { context: 'tags', taggable_type: 'Node' }).uniq }
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  #load_and_authorize_resource
  before_filter :board

  def index
  end

  def show
  end

  def new
  end

  def create
    operation = Group::UpdateService.new(params, board)
    operation.perform!
    if operation.success?
      flash.now[notice] = t('.succeed')
      redirect_to group_path(b.group)
    else
      flash.now[:alert] = t('.failed')
      flash.now[:error] = b.group.human_errors if b.group.human_errors.present?
      render :new
    end
  end

  def update
    operation = Group::UpdateService.new(params, board)
    operation.perform!
    if operation.success?
      flash.now[notice] = t('.succeed')
      redirect_to group_path(b.group)
    else
      flash.now[:alert] = t('.failed')
      flash.now[:error] = b.group.human_errors if b.group.human_errors.present?
      render :edit
    end
  end

  def edit

  end

  def board
    @board = GroupsBoard.new(self)
  end

  def groups_params
    params.require('tag')
      .permit(:name)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_add_nodes_modal.html.slim
.modal.fade#addNodesModal[tabindex="-1" role="dialog" aria-labelledby="addNodesModalLabel"]
  .modal-dialog.modal-lg[role="document"]
    .modal-content
      .modal-header
        button[type="button" class="close" data-dismiss="modal" aria-label="Close"]
          span[aria-hidden="true"] &times;
        h1[class="modal-title" id="addNodesModalLabel"]
          = t('.modal.title')
      .form-group.string.required.mass_mailing_nodes_node_id
            .hidden#mass_mailing_nodes_ids[data-ids="#{b.group_node_ids}"]

      .modal-body
        table.table.table-striped#mass_mailing_nodes[data-source="#{mass_mailing_nodes_url(format: :json)}"]
          thead
            tr
              th = Node.human_attribute_name('id')
              th = Node.human_attribute_name('name')
              th = Node.human_attribute_name('tags')
              th
                input[name="select_all" value="1" type="checkbox"]
          tbody
            - b.all_free_nodes.each do |node|
              tr
                td
                  = node.id
                td
                  = node.name
                td
                  = node.tags.map(&:name).join('; ')
                td
                  input[type='checkbox']
      .modal-footer
        button[type="button" class="btn btn-default" data-dismiss="modal"] Close
        button[type="button" class="btn btn-primary"] Save changes

app/views/groups/_form.html.slim
= simple_form_for(b.group) do |f|
  = f.input :name, required: true
  .form-group.string.required.group_node_id
    #groups_ids[data-ids="#{b.group_node_ids}"]
    table.table#data-table
      thead
        tr
          th
            = Node.human_attribute_name('id')
          th
            = Node.human_attribute_name('name')
          th
            = Node.human_attribute_name(:tags)
          th
            input[name="select_all" value="1" type="checkbox"]
      tbody
        - b.nodes.each do |node|
          tr
            td
              = node.id
            td
              = node.name
            td
              = node.tags.map(&:name).join('; ')
            td
              input[type='checkbox']

  = f.submit class: 'btn btn-primary'

app/views/groups/_nodes_data_table.html.slim
table.table
  thead
    tr
      th
        = Node.human_attribute_name('id')
      th
        = Node.human_attribute_name('name')
      th
        = Node.human_attribute_name('description')
      th
        = t('edit')
      th
        = t('destroy')
  tbody
    - b.group_nodes.each do |n|
      tr
        td
          = n.id
        td
          = n.name
        td
          = n.description_human
        td
          = link_to t('edit'), edit_node_path(n)
        td = link_to t('destroy'), n, method: :delete, data: { confirm: 'Are you sure?' }

app/views/groups/edit.html.slim
h1
  = t('.title')

= render 'form'

= link_to t('show'), group_path(b.group)
br
= link_to t('back'), groups_path

app/views/groups/index.html.slim
.row.header.header_row
  .col-md-11
    h1
      = t('.list')
  .col-md-1
    .header_toolbar.pull-right
      - if can?(:create, Group)
        = link_to glyphicon_with_text('plus', t('.new')), new_group_path, class: 'btn btn-primary pull-right'
br
.row
  .col-md-12
    table.table#nodes[data-source="#{nodes_url(format: :json)}"]
      thead
        tr
          th = t('.id')
          th = t('.name')
          th = t('.node_count')
          th = t('.edit')
      tbody
        - b.groups.each do |group|
          tr
            td = group.id
            td = link_to group.name, group_path(group)
            td = group.taggings_count
            td = link_to t('.edit'), edit_group_path(group)

app/views/groups/new.html.slim
h1
  = t('.group')

= render 'form'

= link_to t('back'), groups_path

app/views/groups/show.html.slim
.row.header.header_row
  .col-md-10
    h1
      = b.group.name
  .col-md-2
    .header_toolbar.pull-right
      = link_to glyphicon_with_text('pencil', 'Edit'), edit_group_path(b.group), class: 'btn btn-primary pull-right'

br
.row
  .col-md-12
    = render 'nodes_data_table'
.row
  .col-md-10
    // = render 'add_nodes_modal'
  //.col-md-2
    .pull-right
      button.btn.btn-success.pull-right[type="bytton" data-toggle="modal" data-target="#addNodesModal"]
        = glyphicon_with_text('plus', t('.add'))
.row
  .col-md-12
    = link_to t('back'), groups_path, class: 'btn btn-default'