config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, skip: [:registrations], controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    get 'cabinet' => 'users/registrations#show'
    get 'cabinet/edit' => 'users/registrations#edit'
    put 'cabinet' => 'users/registrations#update'
  end

  resources :groups
  resources 'nodes'
  resources 'accounts'
  resources 'messages'
  resources 'vk_groups'
  resources 'groups'
  resources :mass_mailings do
    member do
      get :retry
    end
  end

  resources :mass_mailing_nodes, controller: 'mass_mailing_nodes'
  resources :statistics, controller: 'statistics'

  root 'mass_mailings#index'
  resources :node_vks, controller: 'nodes', type: 'Node::Vk'
  resources :node_emails, controller: 'nodes', type: 'Node::Email'

  mount Resque::Server.new, at: "/resque"

end

app/models/mass_mailing.rb
class MassMailing < ActiveRecord::Base
  include Errorable
  has_many :mass_mailing_nodes, dependent: :destroy
  has_many :nodes, through: :mass_mailing_nodes
  has_many :mass_mailing_messages, dependent: :destroy
  has_many :messages, through: :mass_mailing_messages
  belongs_to :sender, class_name: "Account"


  before_create { self.started = Time.now }
  enum status: {
    'success' => 'success',
    'pending' => 'pending',
    'failed' => 'failed',
    'in_progress' => 'in_progress',
    'warning' => 'warning'
  }

  #validate :at_least_one_mailing_node, :message_present?

  accepts_nested_attributes_for :mass_mailing_nodes
  accepts_nested_attributes_for :mass_mailing_messages

  validates :title, length: { minimum: 3 }
#  validates :message_id, presence: true
  validates :mass_mailing_nodes, length: { minimum: 1 }
  validates :mass_mailing_messages, length: { minimum: 1 }

  def message_present?
    message.present?
  end

  def message
    messages.sample
  end

  def at_least_one_mailing_node
    errors.add(:base, 'must add at least one node') if self.mass_mailing_nodes.blank?
    true
  end

  def calculate_status
    case processed_node_counter
    when 0
      self.status = 'pending'
    when less_than_nodes_size
      self.status = 'in_progress'
    when equal_node_size
      calculate_success_or_not
    else
      self.status = 'failed'
    end
  end

  def less_than_nodes_size
    -> (counter) { counter < nodes.size }
  end

  def equal_node_size
    -> (counter) { counter == nodes.size }
  end

  def include_only_error_and_success
    lambda do |array|
      array.size == 2 && array.include?('success') && array.include?('failed')
    end
  end

  def calculate_success_or_not
    children_statuses = mass_mailing_nodes.map(&:status).uniq
    case children_statuses
    when ['failed']
      self.status = 'failed'
      self.finished = Time.now
    when ['success']
      self.status = 'success'
      self.finished = Time.now
    when include_only_error_and_success
      self.status = 'warning'
    else
      fail "Undetermined MassMailing status #{children_statuses}"
    end
  end

  def comment_strategy_proc
    {
      'default' => proc { |_id, _i| true },
      'odd' => proc { |_id, i| i.odd? },
      'even' => proc { |_id, i| i.even? },
      'random' => proc { rand(2) == 1}
    }
  end
end

app/controllers/mass_mailings_controller.rb
class MassMailingsController < ApplicationController
  load_and_authorize_resource
  before_filter :board

  def board
    @board ||= MassMailingsBoard.new(self)
  end

  def index
    respond_to do |format|
      format.html
    end
  end

  # GET /nodes/1
  # GET /nodes/1.json
  def show
  end

  # GET /nodes/new
  def new
  end

  # GET /nodes/1/edit
  # def edit
  # end

  # POST /nodes
  # POST /nodes.json
  def create
    operation = MassMailing::CreateService.new(params, board)
    operation.perform!
    if operation.success?
      redirect_to b.mass_mailing, notice: 'Mass Mailing was successfully created.'
    else
      flash.now[:error] = b.mass_mailing.human_errors if b.mass_mailing.human_errors.present?
      render :new
    end
  end

  def retry
    attributes = board.mass_mailing.attributes
    attributes["mass_mailing_nodes_attributes"] = board.mass_mailing.mass_mailing_nodes.map { |mmn| { "node_id" => mmn.node_id, 'type' => mmn.type } }
    params[:mass_mailing] = attributes
    board.mass_mailing.id = nil
    render :new
  end

  def destroy
    if b.mass_mailing.destroy
      redirect_to mass_mailings_path
    else
      redirect_to mass_mailing_path(b.mass_mailing)
    end
  end

  private

  def mass_mailing_params
    params.require(:mass_mailing).permit(:title, :started,  :sender_id, message_id: [],mass_mailing_nodes_attributes: [:id, :node_id, :_destroy, :type])
  end
end

app/helpers/mass_mailings_helper.rb
module MassMailingsHelper
  def mass_mailing_status(mass_mailing)
    case mass_mailing.status
    when 'success'
      'success'
    when 'warning'
      'warning'
    when 'in_progress'
      'info'
    when 'failed'
      'danger'
    else
      ''
    end
  end

  def mass_mailing_badge(mass_mailing)
    case mass_mailing.status
    when 'success'
      'glyphicon glyphicon-ok-sign'
    when 'warning'
      'glyphicon glyphicon-info-sign'
    when 'in_progress'
      'glyphicon glyphicon-refresh'
    when 'failed'
      'glyphicon glyphicon-remove-sign'
    else
      'glyphicon glyphicon-question-sign'
    end
  end
end

app/views/mass_mailings/_form.html.erb
<%= simple_form_for(b.mass_mailing, url: mass_mailings_url, method: :post) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title, required: true %>
    <!-- <%= f.input :started %> -->
  </div>

  <div class="form-inputs">
    <%= f.input :span, collection: [0, 5, 10, 20, 50, 100], include_blank: false %>
  </div>

  <div class="form-inputs">
    <%= f.input :comment_count, collection: [0, 5, 10, 20, 50, 100], include_blank: false %>
  </div>

  <div class="form-inputs">
    <%= f.input :comment_strategy,
                collection: ['default', 'odd', 'even', 'random'],
                value_method: ->(u) { u },
                label_method: ->(u) { t(".#{u}") },
                include_blank: false %>
  </div>

  <div class="form-inputs">
    <%= f.input :sender_id,
        collection: Account.all,
        label_method: ->(u) { "#{t('social.vk')} #{u.vk_name} | #{u.email_name}" },
        value_method: ->(u) { u.id } %>
    <!-- <%= f.input :started %> -->
  </div>

  <div class="form-inputs">
    <%= f.input :message_id,
                collection: Message.all,
                label_method: ->(m) { m.title },
                value_method: ->(m) { m.id },
                required: true,
                input_html: { multiple: true } %>

  </div>

  <div class="form-group string required mass_mailing_nodes_node_id">
    <div class="hidden" id="mass_mailing_nodes_ids" data-ids="<%= b.mass_mailing_nodes_ids %>"></div>
    <div class="hidden" id="mass_mailing_nodes_types" data-ids="<%= b.mass_mailing_nodes_types %>" ></div>
  </div>

  <h3> <%= I18n.t('activerecord.models.node') %> </h3>

  <table class='table table-striped' id="mass_mailing_nodes" data-source="<%= mass_mailing_nodes_url(format: :json)%>">
    <thead>
      <tr>
        <th><%= Node.human_attribute_name(:id) %></th>
        <th><%= Node.human_attribute_name(:name) %></th>
        <th><%= Node.human_attribute_name(:description) %></th>
        <th><%= Node.human_attribute_name(:tags) %></th>
        <th>Create Post</th>
        <th><input name="select_all" value="1" type="checkbox"></th>
      </tr>
    </thead>

    <tbody>
      <% b.nodes.map do |node| %>
        <tr id='node<%= node.id %>'>
          <td><%= node.id %></td>
          <td><%= link_to(node.name, node) %></td>
          <td><%= truncate(ERB::Util.h(node.description_human), length: 300) %></td>
          <td><%= node.tags.map(&:name).join('; ') %></td>
          <td><input class="type" type='checkbox' <%= (node.is_a? Node::Vk) ? '' : 'disabled' %> %> </td>
          <td><input class="select" type='checkbox' ></td>
        </tr>
      <% end %>
    </tbody>
  </table>


  <div class="form-actions">
    <%= f.button :submit, t('.submit'), class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/mass_mailings/index.html.erb
<div class="row header header_row">
  <div class="col-md-11">
    <h1><%= t('mass_mailings.list') %></h1>
  </div>
  <div class="col-md-1">

    <%= link_to glyphicon_with_text('plus', t('mass_mailings.new')), new_mass_mailing_path, class: 'btn btn-primary pull-right' %>
  </div>
</div>
<br>
<div class="row">
  <div class="col-md-12">
    <table class='table'>
      <thead>
        <tr>
          <th><%= MassMailing.human_attribute_name('id')%></th>
          <th><%= MassMailing.human_attribute_name('title')%></th>
          <th><%= MassMailing.human_attribute_name('message_title')%></th>
          <th><%= MassMailing.human_attribute_name('nodes')%></th>
          <th><%= MassMailing.human_attribute_name('started')%></th>
          <th><%= MassMailing.human_attribute_name('finished')%></th>
          <th><%= t('.retry')%></th>
          <th><%= t('destroy')%></th>
        </tr>
      </thead>

      <tbody>
        <% b.mass_mailings.each do |mass_mailing| %>
          <tr class="<%=mass_mailing_status(mass_mailing)%>">
            <td><%= mass_mailing.id %></td>
            <td><%= link_to mass_mailing.title, mass_mailing %></td>
            <% if mass_mailing.messages.present? %>
              <td>
                <% mass_mailing.messages.each do |message| %>
                  <%= link_to message.title, message %>
                  <br>
                <% end %>
              </td>
            <% else %>
              <td><%= t('.missing.message') %></td>
            <% end %>
            <td><%= mass_mailing.nodes.map(&:name).join(', ') %></td>
            <td><%= time_ago_in_words(mass_mailing.started) if mass_mailing.started %></td>
            <td><%= time_ago_in_words(mass_mailing.finished) if mass_mailing.finished %></td>
            <td><%= link_to t('.retry'), retry_mass_mailing_path(mass_mailing), class: 'btn btn-primary', data: { confirm: t('.confirmation') } %></td>
            <td><%= link_to(t('destroy'), mass_mailing, method: :delete, data: { confirm: t('confirmation') }) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/mass_mailings/new.html.erb
<h1><%= t('mass_mailings.new') %></h1>

<%= render 'form'%>

<%= link_to t('back'), mass_mailings_path %>

app/views/mass_mailings/show.html.slim
- if b.mass_mailing.success?
  .alert.alert-success[role="alert"]
    = t("mass_mailings.status.#{b.mass_mailing.status}_text")
- if b.mass_mailing.failed?
  .alert.alert-danger[role="alert"]
    = t("mass_mailings.status.#{b.mass_mailing.status}_text")
- if b.mass_mailing.pending? || b.mass_mailing.in_progress?
  .alert.alert-info[role="alert"]
    = t("mass_mailings.status.#{b.mass_mailing.status}_text")
- if b.mass_mailing.warning?
  .alert.alert-warning[role="alert"]
    = t("mass_mailings.status.#{b.mass_mailing.status}_text")

.row.header.header_row#header[data-reload="#{should_reload(b.mass_mailing)}"]
  .col-md-9
    h1
      = b.mass_mailing.title
      span.badge
        span[class="#{mass_mailing_badge(b.mass_mailing)}"]
  .col-md-3.pull-right
    => link_to glyphicon_with_text('repeat', t('.retry')), retry_mass_mailing_path(b.mass_mailing), class: 'btn btn-primary', data: { confirm: t('.confirmation') }
    = link_to glyphicon_with_text('duplicate', t('.dublicate')), retry_mass_mailing_path(b.mass_mailing), class: 'btn btn-primary', data: { confirm: t('.confirmation') }
br
.row
  .col-md-12
    - if b.mass_mailing.started
      p
        strong = MassMailing.human_attribute_name(:started)
        |:
        = time_ago_in_words(b.mass_mailing.started)
    - if b.mass_mailing.finished
      p
        strong = MassMailing.human_attribute_name(:finished)
        |:
        = time_ago_in_words(b.mass_mailing.finished)
.row
  .col-md-12
    p
      strong = MassMailing.human_attribute_name(:status)
      |:
      =< t("mass_mailings.status.#{b.mass_mailing.status}")
.row
  .col-md-12
    p
      strong = MassMailing.human_attribute_name(:message)
      |:
      - b.mass_mailing.messages.each do |message|
        =< link_to message.title, message_path(message)

br
.row
  - if b.mass_mailing.mass_mailing_nodes.present?
    .col-md-12
      h2 Статистика по об’єктам
      table.table
        thead
          th Назва
          th Результат відправки
        tbody
          - b.mass_mailing.mass_mailing_nodes.each do |mmn|
            tr[class="#{mass_mailing_status(mmn)}"]
              td
                = mmn.name
              td
                = t("mass_mailings.status.#{mmn.status_text}")
  - else
    .col-md-12
      p
        h2 = t('.mass_mailing_empty')
br
.row
  .col-md-12
    = link_to t('back'), mass_mailings_path, class: 'btn btn-default'