config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, skip: [:registrations], controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    get 'cabinet' => 'users/registrations#show'
    get 'cabinet/edit' => 'users/registrations#edit'
    put 'cabinet' => 'users/registrations#update'
  end

  resources :groups
  resources 'nodes'
  resources 'accounts'
  resources 'messages'
  resources 'vk_groups'
  resources 'groups'
  resources :mass_mailings do
    member do
      get :retry
    end
  end

  resources :mass_mailing_nodes, controller: 'mass_mailing_nodes'
  resources :statistics, controller: 'statistics'

  root 'mass_mailings#index'
  resources :node_vks, controller: 'nodes', type: 'Node::Vk'
  resources :node_emails, controller: 'nodes', type: 'Node::Email'

  mount Resque::Server.new, at: "/resque"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Messenger" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
    <%= javascript_include_tag 'head.min' %>
    <%= headjs_include_tag 'application' %>
  </head>
  <body data-class-name = "<%=js_class_name%>" data-locale="<%= I18n.locale %>" data-default-locale="<%= I18n.default_locale %>">
    <div class="navbar navbar-default navbar-static-top header">
      <div class="container">
        <div class="row">
          <div class="col-sm-3">
            <a class="navbar-brand logo" href="/">
              <%= image_tag('sign.png') %>
            </a>
          </div>
          <div class="col-sm-6 center">
              <h2>Міністерство оборони України</h2>
              <h3>Управління інформаційних технологій</h3>
              <h4>Проект "Месседж"</h4>
          </div>
        </div>


      </div>
    </div>
    <div class="navbar navbar-default navbar-static-top second">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <hr />
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= nav_link t('nodes.plural'), nodes_path  %></li>
            <li><%= nav_link t('groups.plural'), groups_path  %></li>
            <li><%= nav_link t('nodes.messages'), messages_path  %></li>
            <li><%= nav_link t('accounts.plural'), accounts_path  %></li>
            <li><%= nav_link t('nodes.massmailings'), mass_mailings_path  %></li>
            <li><%= nav_link t('statistics.index.header'), statistics_path %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
              <% if can? :access, :rails_admin %>
                <li><%= link_to glyphicon_with_text('control-sign', "#{t('devise.registrations.show.admin')}"), rails_admin_path, method: :get%></li>
              <% end %>
              <li><%= link_to glyphicon_with_text('info-sign', "#{t('devise.registrations.show.cabinet')}"), cabinet_path%></li>
              <li><%= link_to t('log_out'), destroy_user_session_path, method: :delete%></li>
            <%end%>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12 page_content_wrapper_narrow" >
          <!-- < bootstrap_flash > -->
          <%= flash_messages %>
          <%= yield %>
        </div>
      </div><!--/row-->



    </div> <!-- /container -->
    <footer>
      <div class="footer_application">
        <div class="container">
          <div class="copyright">
            <!-- <img src="assets/images/mil-grey.jpg" > -->
            <p>&copy; <%=t('copy') %> </p>
          </div>
        </div>
      </div>
    </footer>

  </body>
</html>